<h1>Quiñonez Jair Examen</h1>

## 1) Examen

In [87]:
## 2) 
import numpy as np 
arreglo_cero = np.zeros(10)
print(arreglo_cero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [88]:
## 3)

In [89]:
arreglo_cero_con_uno = np.zeros(10)
arreglo_cero_con_uno[4] = 1
print(arreglo_cero)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [90]:
## 4) 

In [91]:
arreglo_cincuenta = np.arange(50)
cambiado = arreglo_cincuenta[::-1]
print(cambiado)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [92]:
## 5)

In [93]:
matriz_por_tres = np.arange(9).reshape(3,3)
print(matriz_por_tres)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [94]:
## 6) 

In [95]:
import numpy as np
arreglo = [1,2,0,0,4,0]

no_cero = np.nonzero(arreglo)
print(f'Los indices son:{no_cero}')

Los indices son:(array([0, 1, 4], dtype=int64),)


In [96]:
## 7) 

In [97]:
matriz_identidad = np.eye(3)
print(matriz_identidad)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [98]:
## 8) 

In [99]:
matriz_radom_tres = np.random.random((3,3,3))
print(matriz_radom_tres)

[[[0.48441795 0.72295732 0.26361239]
  [0.74203996 0.94850517 0.70252109]
  [0.31449318 0.05749017 0.82850321]]

 [[0.07797769 0.74539708 0.13175067]
  [0.72291666 0.56456996 0.23689024]
  [0.39024557 0.71262466 0.83255246]]

 [[0.1997431  0.08511762 0.97928966]
  [0.43185088 0.25539565 0.12918438]
  [0.25445213 0.36855183 0.09175753]]]


In [100]:
## 9) 

In [101]:
matriz_diez = np.random.random((10,10))
print(matriz_diez)
print(f'El mayor: {matriz_diez.max()}')
print(f'El menor: {matriz_diez.min()}')


[[0.40722607 0.01558753 0.08346411 0.59810292 0.86384218 0.4048329
  0.93462212 0.13075298 0.67763957 0.14694493]
 [0.93107516 0.81882097 0.03253356 0.76185902 0.29705901 0.65677858
  0.48360569 0.4467438  0.13319864 0.15522616]
 [0.24058983 0.74321847 0.25351982 0.1913076  0.02350987 0.98569681
  0.5407269  0.38942283 0.53687805 0.39954473]
 [0.85892649 0.62493197 0.05421508 0.25040739 0.55520906 0.37692034
  0.81307695 0.00419109 0.80683271 0.09535143]
 [0.48759716 0.43350813 0.92336485 0.47662474 0.74133048 0.40989293
  0.47094188 0.23203858 0.9221709  0.91016994]
 [0.43553512 0.01971853 0.52215805 0.85871467 0.70318465 0.36638804
  0.64517787 0.14420041 0.55810735 0.9857186 ]
 [0.91658349 0.17041849 0.32316058 0.35092576 0.88406943 0.99634829
  0.26889535 0.0779694  0.37721002 0.26530515]
 [0.3017566  0.4571905  0.02732279 0.06994786 0.18461282 0.27723215
  0.99342404 0.27370717 0.94153843 0.31904258]
 [0.63711662 0.51249477 0.13715353 0.94488849 0.14143583 0.5234299
  0.28262511 0

In [102]:
## 10) 

In [103]:
from scipy import misc
from scipy import ndimage

imagen = misc.face()
rgb = np.unique(imagen.reshape(-1, imagen.shape[2]), axis=0)
print(rgb)
print('--> 2 Colores')

[[  0   0   5]
 [  0   0   7]
 [  0   0   9]
 ...
 [255 248 255]
 [255 249 255]
 [255 252 255]]
--> 2 Colores


In [104]:
## 11) 


In [105]:

import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
import pandas as pd
lista_serie = pd.Series(mylist)
arreglo_serie = pd.Series(myarr)
dicci_serie = pd.Series(mydict)
print(lista_serie)
print(arreglo_serie)
print(dicci_serie)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [106]:
## 12) 


In [107]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
# Transformar la serie en dataframe y hacer una columna indice
print(ser)
dataFrame = ser.to_frame().reset_index
print(dataFrame)

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64
<bound method DataFrame.reset_index of     0
a   0
b   1
c   2
e   3
d   4
f   5
g   6
h   7
i   8
j   9
k  10
l  11
m  12
n  13
o  14
p  15
q  16
r  17
s  18
t  19
u  20
v  21
w  22
x  23
y  24
z  25>


In [108]:
## 13) 

In [109]:

import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
#a = pd.DataFrame
dataFrame_series = pd.DataFrame({'Primera': ser1,'Segunda': ser2})
print(dataFrame_series)


   Primera  Segunda
0        a        0
1        b        1
2        c        2
3        e        3
4        d        4
5        f        5
6        g        6
7        h        7
8        i        8
9        j        9
10       k       10
11       l       11
12       m       12
13       n       13
14       o       14
15       p       15
16       q       16
17       r       17
18       s       18
19       t       19
20       u       20
21       v       21
22       w       22
23       x       23
24       y       24
25       z       25


In [110]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
test= ser1[-ser1.isin(ser2)]
print('Los que no estan son')
print(test)

Los que no estan son
0    1
1    2
2    3
dtype: int64


In [111]:
## 15) ¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

a_notB = ser1[-ser1.isin(ser2)]
b_notA = ser2[-ser2.isin(ser1)]

no_comun = np.append(a_notB,b_notA)
print('NO COMUNES EN AMBAS')
print(no_comun)

NO COMUNES EN AMBAS
[1 2 3 6 7 8]


In [112]:
## 16)
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
repe = ser.value_counts()
print(repe)


c    8
e    7
a    5
b    3
d    2
f    2
g    2
h    1
dtype: int64


In [113]:
## 17)
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
print(f'La SERIE \n{ser}')
print(f'REPETIDOS- \nVALOR/REPE \n{ser.value_counts()}')
ser[-ser.isin(ser.value_counts().index[:2])] = 0
print(f'Cambiados pos cero \n{ser}')

La SERIE 
0     2
1     2
2     4
3     2
4     4
5     3
6     1
7     3
8     2
9     3
10    2
11    3
dtype: int32
REPETIDOS- 
VALOR/REPE 
2    5
3    4
4    2
1    1
dtype: int64
Cambiados pos cero 
0     2
1     2
2     0
3     2
4     0
5     3
6     0
7     3
8     2
9     3
10    2
11    3
dtype: int32


In [114]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?
ser = pd.Series(np.random.randint(1, 10, 35))
#shape(7,5)
dataFrame_transfor = pd.DataFrame(ser.values.reshape(7,5))
print(dataFrame_transfor)


   0  1  2  3  4
0  6  2  4  2  7
1  8  8  5  2  5
2  2  2  5  7  7
3  2  5  7  8  1
4  4  9  5  6  8
5  2  4  5  4  9
6  5  6  6  9  8


In [115]:
## 19) ¿Obtener los valores de una serie conociendo la posicion por indice?
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
# a e i o u

indice = ser.take(pos)
print(indice)

0     a
4     e
8     i
14    o
20    u
dtype: object


In [116]:
## 20) ¿Como anadir series vertical u horizontalmente a un DataFrame?
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
dataFrame_agregado = pd.concat([ser1,ser2], axis=1)
print(dataFrame_agregado)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [117]:
## 21)¿Obtener la media de una serie agrupada por otra serie?
#`groupby` tambien esta disponible en series.
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
pesos = pd.Series(np.linspace(1, 10, 10))
print(pesos.tolist())
print(frutas.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']

# Los valores van a cambiar por ser random
# apple     6.0
# banana    4.0
# carrot    5.8
# dtype: float64
media = pesos.groupby(frutas).mean()
print(f'La MEDIA ES \n{media}')


[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['zanahoria', 'banana', 'zanahoria', 'manzana', 'banana', 'zanahoria', 'zanahoria', 'banana', 'banana', 'zanahoria']
La MEDIA ES 
banana       6.0
manzana      4.0
zanahoria    5.4
dtype: float64


In [118]:
## 22)¿Como importar solo columnas especificas de un archivo csv?

##https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv.
path = 'https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv'
data_importado = pd.read_csv(path)
print('EL COMPLETO')
print(data_importado)
colums = ['nox','rad','tax','zn']
data_importado_especificas = pd.read_csv(path, usecols=colums)
print('\n\nESPECIFICAS')
print(data_importado_especificas)

EL COMPLETO
        crim    zn  indus  chas    nox     rm   age     dis  rad  tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2  