In [1]:
import numpy as np

In [3]:
arreglo_grados = np.array([0,30,45,60,90])
arreglo_grados

array([ 0, 30, 45, 60, 90])

In [4]:
arreglo_radianes = arreglo_grados * np.pi / 180 

In [6]:
arreglo_radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [8]:
np.sin(arreglo_radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [9]:
np.cos(arreglo_radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [10]:
np.tan(arreglo_radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [14]:
numero_random = np.random.randint(
    11 #[0, 11[
)
numero_random

4

In [18]:
numero_randomo_negativo = np.random.randint(
    -9, #[-9, 2[
    2
)
numero_randomo_negativo

-3

In [19]:
arreglo_random = np.random.randint(
    10, #inicio 
    20, #fin 
    8   #numero de elementos
)
arreglo_random

array([10, 13, 15, 13, 18, 17, 10, 14])

In [24]:
np.random.rand(9)# 9 elementos
np.random.rand(3,2) #6 elementos (3x2 dimensiones )

array([[0.0601117 , 0.31949501],
       [0.1289122 , 0.80702967],
       [0.22125451, 0.27132197]])

In [26]:
np.average(arreglo_random)

13.75

In [27]:
np.mean(arreglo_random)

13.75

In [28]:
np.median(arreglo_random)

13.5

In [29]:
np.std(arreglo_random)

2.7271780286589284

In [30]:
np.var(arreglo_random)

7.4375

In [31]:
arreglo_random.mean()

13.75